name: mobile_pos
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.1.0
  url_launcher: ^6.2.0
  app_links: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_grid_button: ^2.1.0
  uuid: ^4.0.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true